### PR TITLE
variables.tf: transition_to_ia -- add AFTER_1_DAY as valid value

### PR DESCRIPTION
**Pull request by michw**
## what

- Add `AFTER_1_DAY` as a valid value for [transition_to_ia](https://github.com/cloudposse/terraform-aws-efs#input_transition_to_ia)
- Add `efs_file_system_policy` resource

## why

- `AFTER_1_DAY` is a [valid value](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#transition_to_ia) for transition_to_ia argument for lifecycle policy.
- `efs_file_system_policy` resource was missing.

### CODE REVIEW

**Comment by michw** [comment]
anybody ?

**Comment by Gowiem** [comment]
Hey @michw, sadly this is blocked as we need to upgrade the VPC module version in our `examples/complete`. See here on a similar issue: https://github.com/cloudposse/terraform-aws-rds/pull/157#pullrequestreview-1706452738

Can you give that a shot and push your changes and we'll work to get this reviewed and merged?

**Comment by michw** [comment]
FWIW it passed when running local with `make docker/test` :grin:

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
Thanks for the hard work and patience @michw. This will be released as https://github.com/cloudposse/terraform-aws-efs/releases/tag/0.35.0 shortly 👍

**Comment by michw** [comment]
No worries, it was fun.

**Pull request merged**
