### PR TITLE
BLOCKED by SG: Add `efs_backup_policy_enabled`

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Add `efs_backup_policy_enabled`

## why
* Provides an Elastic File System (EFS) Backup Policy resource. Backup policies turn automatic backups on or off for an existing file system.

## references
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_backup_policy

### CODE REVIEW

**Review by osterman — DISMISSED** [review]

**Comment by chris-str-cst** [comment]
+1  for this one @nitrocode :) When will this be merged?

**Comment by agustingarciaflores** [comment]
I would be awesome if this gets merged, it will make enabling backups on EFS so much cleaner.

**Comment by nitrocode** [comment]
Once the sg module is upgraded to 0.4.0. This will happen soon but no eta at the moment.

**Comment by nitrocode** [comment]
Thanks for your contribution! This has been released as version [0.32.0](https://github.com/cloudposse/terraform-aws-efs/releases/tag/0.32.0).

**Pull request closed without merging**
