### PR TITLE
Remove Garbage

### PR DESCRIPTION
**Pull request by NIXKnight**
* Create EFS resources only.
* Security group will be provided to you. Don't wander off.
* No need of module inside of a module bloatware.

### CODE REVIEW

**Comment by nitrocode** [comment]
@NIXKnight why revert all the security group 4.x related changes?

**Comment by NIXKnight** [comment]
@nitrocode I intended to do it in my own fork of the repo, just for my personal (concept) use case. But I accidentally create the PR in the main repo. I apologize.

In my case I am managing security groups using a separate module. I would like to not create a redundant security group for EFS using this module. Hence I made this change to my own fork.

However, before I made the change in my fork, I accidentally created this PR in the main repo. I apologize.

**Comment by nitrocode** [comment]
@NIXKnight if you use the latest version here, you can set `create_security_group = false` to disable the sg resource within the module and use a sg module from outside this module, no ?

**Comment by NIXKnight** [comment]
@nitrocode I took some time to study the module. That's a good option you have mentioned. I will use the latest release of the module. Thanks.

**Pull request closed without merging**
