### PR TITLE
bugfix: secondary_gids ignored in acces point creation

### PR DESCRIPTION
**Pull request by juan-acevedo-ntt**
## what
* Check for additional GID when creating a access point
* Access point example added

## why
* The secondary_gids was ignored

### CODE REVIEW

**Review by juan-acevedo-ntt — COMMENTED** [review]
Thanks

**Comment by nitrocode** [comment]
Thanks for your contribution! This has been released as version [0.32.0](https://github.com/cloudposse/terraform-aws-efs/releases/tag/0.32.0).

**Pull request closed without merging**
